Feat: Произведен рефакторинг приложения
sigmaclap/java-shareit pull request #4
Opened 2023-06-22 19:20 UTC by sigmaclap

Приложение разделено на сервис с валидацией и сервер с бизнес логикой
add: Docker - DockerCompose

2023-06-23 20:32 UTC, Fleaman777 requested changes

2023-06-23 20:32 UTC, Fleaman777 commented on docker-compose.yaml
> +    image: postgres:latest
лучше указываешь конкретную версию имеджа, а не просто latest,
так безопасней, т.к. меньше шансов нарваться на версию базового имеджа, с которым текущая версия приложения не будет работать,
то же относится и к Dockerfile

(но в Dockerfile у тебя все хорошо)

2023-06-23 20:32 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/gateway/exceptions/ErrorHandler.java
> +        return new ErrorResponse("Произошла непредвиденная ошибка.");
В сообщениях об ошибке тоже хорошо бы придерживаться одного стиля, в данном слуае языка

2023-06-23 20:32 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/gateway/request/ItemRequestController.java
> +        log.info("Get all item request by owner " + userId);
в логгере удобно использовать плейсхолдер {} для добавления аргументов

2023-06-23 20:32 UTC, Fleaman777 commented on server/src/main/resources/application.properties
> +spring.datasource.username=admin
для просечивания дефолтного значения переемнной можно использовать такую конструкцию spring.datasource.username=${POSTGRES_USER:admin}
она означает, что если, в докер-компосе не просетать переменную POSTGRES_USER, то будет использоваться дефлотное значение admin


но у тебя здесь хорошо работает другой момент, конкретно в этом примере,  можно использовать спринговую перменную SPRING_DATASOURCE_USERNAME, тогда можно будет явно не указыть эту переменную application.yaml,

2023-06-24 14:12 UTC, sigmaclap commented on server/src/main/resources/application.properties
> +spring.datasource.username=admin
Спасибо за ревью! и за ценные комментарии, которые помогают улучшить навыки. 👍

2023-06-25 10:41 UTC, Fleaman777 approved these changes

2023-06-25 10:41 UTC, Fleaman777 commented on server/src/test/java/ru/practicum/shareit/user/UserServiceImplIntegrationTest.java
> +}
за тесты респект)

2023-06-25 10:41 UTC, Fleaman777 commented on server/src/main/resources/application.properties
> +spring.datasource.password=SPRING_DATASOURCE_PASSWORD
да в целом, можно оставить как было, хорший вариант, 
или если хочется как бы переопределить спринговую переменную, можно использовать немного другое название переменной 
например, 
 spring.datasource.password=${DATABASE_PASSWORD:admin}

2023-07-03 11:44 UTC, merged